Summer2023
CASTOR-telescope/ETC_frontend pull request #10
Opened 2023-10-16 00:15 UTC by Dhananjhay

The Graphical User Interface (GUI) now hosts three more new functionalities: uvmos spectroscopy, grism spectroscopy and transit simulation.

2023-10-22 00:36 UTC, BearBearCodes requested changes
Thanks so much for all of this incredible work @Dhananjhay! As I noted in my comment [here](https://github.com/CASTOR-telescope/ETC/pull/12#discussion_r1352339108), it's next to impossible for me to test this code, so I will approve this PR and you can verify your code works on the CANFAR servers.

One small thing before I merge this PR: would you be able to add a note in the README telling users that they will need to modify `STELLAR_MODEL_DIR` in build.sh if they want to run the frontend on their local machine? They may need to modify variables elsewhere, too (if so, please note them in the README).

If you want, I also left a review comment for apt-install.sh that you can address before I merge this PR (i.e., install gcc and g++ by modifying the Dockerfile, not via modifying apt-install.sh).

2023-10-22 00:36 UTC, BearBearCodes commented on docker/apt-install.sh
Like in the ETC's PR [#23](https://github.com/CASTOR-telescope/ETC/pull/23), the best way to install gcc and g++ is to modify the Dockerfile. I (or you) can modify it before/after I merge this PR, and you can double-check that it works well.

You can see how I changed this file and the Dockerfile in the ETC's PR [#24](https://github.com/CASTOR-telescope/ETC/pull/24)

2023-11-06 05:03 UTC, Dhananjhay commented on docker/apt-install.sh
Hey Isaac! Thank you very much for your feedback :D. I can add a note in the README warning users prior on how to change build.sh and what variables to change for building local container but where in README file should I add that? I don't see any particular section for local build instructions. Also, I moved installation of gcc and g++ compilers to Dockerfile from apt-install.sh and it seems to be working just fine. 

Once again, thank you very much your excellent feedback!

2023-11-06 20:06 UTC, BearBearCodes commented on docker/apt-install.sh
Hi @Dhananjhay, sorry for the delayed reply. Yes, I think adding a new section for building the project locally would be a good idea, as well as adding this new section to the table of contents at the top of the README. Feel free to structure this section how you want :)

Thanks for moving gcc and g++ to the Dockerfile as well! I also just realized that the README still has my name as the author... While you are adding the README section, could you also modify the authors to add your name and/or change it to "FORECASTOR Team"? For example, on the ETC repository I've written "FORECASTOR Team - 2022-2023" as the authors.

2023-11-06 20:08 UTC, BearBearCodes approved these changes

2023-11-13 23:24 UTC, merged

2023-11-13 23:32 UTC, Dhananjhay commented on docker/apt-install.sh
Hey @BearBearCodes! Sorry for the delayed response. I have successfully added instructions for local build and merged the feature branch `summer2023` with the master branch. Now, should I create separate PRs to update CHANGELOG.md files for both repositories?

2023-11-14 01:52 UTC, BearBearCodes commented on docker/apt-install.sh
Hi @Dhananjhay, no worries at all! Yes, please go ahead and submit PRs to update the CHANGELOG.md (this one I don't need to review). Thank you again for the exceptional work!

2023-11-14 01:59 UTC, BearBearCodes commented on docker/apt-install.sh
BTW @Dhananjhay, I was just notified ~2 hrs ago that several packages have a vulnerability that has been patched. I've merged the PRs fixing these vulnerabilities, but you will need to update your local build to match the remote. Hopefully nothing breaks (any image pushed to CANFAR should be fine, since it is not downloading directly from this repo)

2023-11-14 05:33 UTC, BearBearCodes commented on docker/apt-install.sh
Ah shoot, that's probably because I overhauled the photometry calculations and the frontend hasn't been updated yet... Do you know if it's possible to just add a big warning at the top of the photometry page telling users that (only) the photometry page is out-of-date and non-functional at the moment? For now, the user should use the Python ETC for synthetic photometry. I will fix this ASAP, but I'm not sure if I can get to it these next few weeks... :/

2023-11-27 05:45 UTC, Dhananjhay commented on docker/apt-install.sh
Hey @BearBearCodes, sorry for the late reply. Sounds like a good idea, I'll add a disclaimer. I am running a little busy lately but in the coming week or so, I'll do as mentioned above and upload the final docker images on Harbor registry. I hope that is okay :).

2023-11-27 08:57 UTC, BearBearCodes commented on docker/apt-install.sh
Hi Dhananjhay, no worries at all. The end of the school semester is always very busy :')